import { MaterialStyle, RunningIndicatorStyle } from '../store/useThemeStore';

export type PresetCategory =
  | 'All'
  | 'Australiana'
  | 'Cyberpunk'
  | 'Nature & Ethereal'
  | 'Minimalist'
  | 'Retro & Aero';

export interface ThemePreset {
  id: string;
  name: string;
  category: Exclude<PresetCategory, 'All'>;
  description: string;
  accentColor: string;
  secondaryAccent: string;
  isLightMode: boolean;
  taskbarMode: 'blur' | 'gradient';
  materialStyle?: MaterialStyle;
  dockMode?: boolean;
  dockMargin?: number;
  runningIndicatorStyle?: RunningIndicatorStyle;
  cornerRadius: number;
  borderThickness?: number;
  taskbarBlur: number;
  startMenuBlur: number;
  notificationBlur: number;
  taskbarOpacity?: number;
  startMenuOpacity?: number;
  notificationOpacity?: number;
  noiseOpacity?: number;
  tintSaturation?: number;
  hideRecommended: boolean;
  compactSearch: boolean;
  dynamicNotificationHeight: boolean;
  removeDropShadows: boolean;
  wallpaperFileName?: string;
  wallpaperUrl: string;
  previewGradient: string;
}

export const PRESET_CATEGORIES: PresetCategory[] = [
  'All',
  'Australiana',
  'Cyberpunk',
  'Nature & Ethereal',
  'Minimalist',
  'Retro & Aero',
];

export const THEME_PRESETS: ThemePreset[] = [
  // ------------------------------------------------------------
  // Australiana Category
  // ------------------------------------------------------------
  {
    id: 'uluru-red-centre',
    name: 'Uluru Red Centre Ochre',
    category: 'Australiana',
    description: 'Rich terracotta red sands, ancient sandstone textures, and warm amber gold sunbursts from the Australian Red Centre.',
    accentColor: '#C2410C',
    secondaryAccent: '#F59E0B',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 10,
    taskbarBlur: 20,
    startMenuBlur: 22,
    notificationBlur: 20,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'uluru-red-centre.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="sky" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="%23451a03"/><stop offset="60%" stop-color="%237c2d12"/><stop offset="100%" stop-color="%23c2410c"/></linearGradient><radialGradient id="sun" cx="75%" cy="35%" r="50%"><stop offset="0%" stop-color="%23f59e0b" stop-opacity="0.45"/><stop offset="100%" stop-color="%23451a03" stop-opacity="0"/></radialGradient></defs><rect width="100%" height="100%" fill="url(%23sky)"/><rect width="100%" height="100%" fill="url(%23sun)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #451a03 0%, #c2410c 50%, #f59e0b 100%)',
  },
  {
    id: 'sydney-harbour',
    name: 'Sydney Harbour & Southern Cross',
    category: 'Australiana',
    description: 'Majestic deep Pacific harbor navy paired with shimmering Southern Cross champagne gold and crisp WinUI 3 glass.',
    accentColor: '#D4AF37',
    secondaryAccent: '#1E3A8A',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 10,
    taskbarBlur: 18,
    startMenuBlur: 20,
    notificationBlur: 18,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'sydney-harbour.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="harbour" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="%23020617"/><stop offset="50%" stop-color="%230f172a"/><stop offset="100%" stop-color="%231e3a8a"/></linearGradient><radialGradient id="cross" cx="50%" cy="30%" r="45%"><stop offset="0%" stop-color="%23d4af37" stop-opacity="0.35"/><stop offset="100%" stop-color="%23020617" stop-opacity="0"/></radialGradient></defs><rect width="100%" height="100%" fill="url(%23harbour)"/><rect width="100%" height="100%" fill="url(%23cross)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #020617 0%, #1e3a8a 50%, #d4af37 100%)',
  },
  {
    id: 'great-barrier-reef',
    name: 'Great Barrier Reef & Whitsundays',
    category: 'Australiana',
    description: 'Vibrant turquoise coral waters, Whitsunday azure ripples, and rounded floating island dock mode.',
    accentColor: '#06B6D4',
    secondaryAccent: '#0284C7',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    dockMode: true,
    dockMargin: 16,
    cornerRadius: 16,
    taskbarBlur: 22,
    startMenuBlur: 24,
    notificationBlur: 22,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'great-barrier-reef.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="reef" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23083344"/><stop offset="50%" stop-color="%230284c7"/><stop offset="100%" stop-color="%2306b6d4"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23reef)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #083344 0%, #0284c7 50%, #06b6d4 100%)',
  },
  {
    id: 'federation-midnight',
    name: 'Federation Midnight & Eureka',
    category: 'Australiana',
    description: 'Historic Eureka Stockade midnight blue, starburst crimson, and angular sharp-edged contrast.',
    accentColor: '#1D4ED8',
    secondaryAccent: '#DC2626',
    isLightMode: false,
    taskbarMode: 'gradient',
    materialStyle: 'linear-gradient',
    cornerRadius: 8,
    taskbarBlur: 16,
    startMenuBlur: 18,
    notificationBlur: 18,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'federation-midnight.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="eureka" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23030712"/><stop offset="50%" stop-color="%231d4ed8"/><stop offset="100%" stop-color="%23dc2626"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23eureka)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #030712 0%, #1d4ed8 50%, #dc2626 100%)',
  },
  {
    id: 'canberra-parliament',
    name: 'Canberra Parliament & Wattle',
    category: 'Australiana',
    description: 'Distinguished parliamentary deep green matched with bright golden wattle blossom highlights and smooth pill geometry.',
    accentColor: '#00843D',
    secondaryAccent: '#FFCD00',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 14,
    taskbarBlur: 20,
    startMenuBlur: 22,
    notificationBlur: 20,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'canberra-parliament.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="parl" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23052e16"/><stop offset="50%" stop-color="%2300843d"/><stop offset="100%" stop-color="%23ffcd00"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23parl)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #052e16 0%, #00843d 50%, #ffcd00 100%)',
  },
  {
    id: 'canberra-autumn',
    name: 'Canberra Autumn & Telstra Tower',
    category: 'Australiana',
    description: 'Cozy autumn oak foliage around Lake Burley Griffin with crisp golden amber and russet evening hues.',
    accentColor: '#D97706',
    secondaryAccent: '#92400E',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 12,
    taskbarBlur: 20,
    startMenuBlur: 22,
    notificationBlur: 20,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'canberra-autumn.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="aut" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%231c1917"/><stop offset="50%" stop-color="%2392400e"/><stop offset="100%" stop-color="%23d97706"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23aut)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #1c1917 0%, #92400e 50%, #d97706 100%)',
  },

  // ------------------------------------------------------------
  // Cyberpunk Category
  // ------------------------------------------------------------
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon Noir',
    category: 'Cyberpunk',
    description: 'Raw OLED pure black glass with high-voltage magenta laser strikes, cyan tracers, and sharp zero-radius geometry.',
    accentColor: '#FF007F',
    secondaryAccent: '#00F3FF',
    isLightMode: false,
    taskbarMode: 'gradient',
    materialStyle: 'pure-black-neon',
    runningIndicatorStyle: 'glow',
    cornerRadius: 0,
    taskbarBlur: 25,
    startMenuBlur: 25,
    notificationBlur: 25,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: true,
    wallpaperFileName: 'cyberpunk-neon.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23050508"/><stop offset="50%" stop-color="%230d0221"/><stop offset="100%" stop-color="%23190028"/></linearGradient><radialGradient id="glow" cx="70%" cy="30%" r="60%"><stop offset="0%" stop-color="%23ff007f" stop-opacity="0.35"/><stop offset="100%" stop-color="%23000000" stop-opacity="0"/></radialGradient><radialGradient id="glow2" cx="20%" cy="80%" r="50%"><stop offset="0%" stop-color="%2300f3ff" stop-opacity="0.25"/><stop offset="100%" stop-color="%23000000" stop-opacity="0"/></radialGradient></defs><rect width="100%" height="100%" fill="url(%23bg)"/><rect width="100%" height="100%" fill="url(%23glow)"/><rect width="100%" height="100%" fill="url(%23glow2)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #050508 0%, #ff007f 50%, #00f3ff 100%)',
  },
  {
    id: 'sunset-synthwave',
    name: 'Sunset Synthwave & Outrun',
    category: 'Cyberpunk',
    description: '1984 retro-futuristic horizon featuring blazing orange dusk gradients, neon magenta grids, and synth aesthetic.',
    accentColor: '#FF5722',
    secondaryAccent: '#E91E63',
    isLightMode: false,
    taskbarMode: 'gradient',
    materialStyle: 'linear-gradient',
    runningIndicatorStyle: 'standard',
    cornerRadius: 6,
    taskbarBlur: 20,
    startMenuBlur: 22,
    notificationBlur: 22,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'sunset-synthwave.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="synth" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%231a052e"/><stop offset="50%" stop-color="%23e91e63"/><stop offset="100%" stop-color="%23ff5722"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23synth)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #1a052e 0%, #e91e63 50%, #ff5722 100%)',
  },
  {
    id: 'tokyo-neon-rain',
    name: 'Tokyo Neon Rain & Arcade',
    category: 'Cyberpunk',
    description: 'Shinjuku midnight streetscape with electric arcade lime green, neon violet reflections, and dot taskbar indicators.',
    accentColor: '#A3E635',
    secondaryAccent: '#A855F7',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'pure-black-neon',
    runningIndicatorStyle: 'dot',
    cornerRadius: 4,
    taskbarBlur: 22,
    startMenuBlur: 22,
    notificationBlur: 22,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'tokyo-neon.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="tokyo" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%2309090b"/><stop offset="50%" stop-color="%23a855f7"/><stop offset="100%" stop-color="%23a3e635"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23tokyo)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #09090b 0%, #a855f7 50%, #a3e635 100%)',
  },

  // ------------------------------------------------------------
  // Nature & Ethereal Category
  // ------------------------------------------------------------
  {
    id: 'deep-ocean',
    name: 'Deep Ocean Bioluminescence',
    category: 'Nature & Ethereal',
    description: 'Midnight abyssal trench depths lit by vivid bioluminescent teal glow and thermal pink accents.',
    accentColor: '#64FFDA',
    secondaryAccent: '#FF007F',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    runningIndicatorStyle: 'glow',
    cornerRadius: 10,
    taskbarBlur: 24,
    startMenuBlur: 26,
    notificationBlur: 24,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'deep-ocean.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="ocean" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23021526"/><stop offset="50%" stop-color="%2303346e"/><stop offset="100%" stop-color="%2364ffda"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23ocean)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #021526 0%, #03346e 50%, #64ffda 100%)',
  },
  {
    id: 'ethereal-sakura',
    name: 'Ethereal Sakura & Cloud Mist',
    category: 'Nature & Ethereal',
    description: 'Delicate blossom pinks and lavender cloud mist floating on a floating dock pill with frosted acrylic translucency.',
    accentColor: '#F472B6',
    secondaryAccent: '#C084FC',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    dockMode: true,
    dockMargin: 18,
    cornerRadius: 16,
    taskbarBlur: 26,
    startMenuBlur: 28,
    notificationBlur: 26,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'sakura.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="sakura" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%232e1065"/><stop offset="50%" stop-color="%23c084fc"/><stop offset="100%" stop-color="%23f472b6"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23sakura)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #2e1065 0%, #c084fc 50%, #f472b6 100%)',
  },
  {
    id: 'nordic-frost',
    name: 'Nordic Frost & Aurora',
    category: 'Nature & Ethereal',
    description: 'Arctic sub-zero chill with glacial cyan borders, polar aurora borealis emerald light, and frosted glass.',
    accentColor: '#38BDF8',
    secondaryAccent: '#10B981',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 12,
    taskbarBlur: 25,
    startMenuBlur: 28,
    notificationBlur: 25,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'nordic-frost.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="nordic" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%230b132b"/><stop offset="50%" stop-color="%2338bdf8"/><stop offset="100%" stop-color="%2310b981"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23nordic)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #0b132b 0%, #38bdf8 50%, #10b981 100%)',
  },
  {
    id: 'forest-sage',
    name: 'Forest Sage & Warm Brass',
    category: 'Nature & Ethereal',
    description: 'Calming botanical evergreen canopy balanced with antique brass metallic trim and tranquil aesthetics.',
    accentColor: '#2D5A43',
    secondaryAccent: '#C9A84E',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 8,
    taskbarBlur: 16,
    startMenuBlur: 18,
    notificationBlur: 16,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'forest-sage.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="forest" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23061e12"/><stop offset="50%" stop-color="%232d5a43"/><stop offset="100%" stop-color="%23c9a84e"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23forest)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #061e12 0%, #2d5a43 50%, #c9a84e 100%)',
  },

  // ------------------------------------------------------------
  // Minimalist Category
  // ------------------------------------------------------------
  {
    id: 'minimalist-zen',
    name: 'Minimalist Zen',
    category: 'Minimalist',
    description: 'Understated matte slate surfaces, Japanese moss celadon accents, organic round corners, and zero distractions.',
    accentColor: '#8FBC8F',
    secondaryAccent: '#FFD700',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'matte-slate',
    runningIndicatorStyle: 'dot',
    cornerRadius: 20,
    taskbarBlur: 5,
    startMenuBlur: 10,
    notificationBlur: 10,
    hideRecommended: true,
    compactSearch: true,
    dynamicNotificationHeight: true,
    removeDropShadows: true,
    wallpaperFileName: 'zen.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><rect width="100%" height="100%" fill="%2318181b"/></svg>',
    previewGradient: 'linear-gradient(135deg, #18181b 0%, #27272a 50%, #8fbc8f 100%)',
  },
  {
    id: 'royal-obsidian',
    name: 'Royal Obsidian & Velvet Gold',
    category: 'Minimalist',
    description: 'Sumptuous imperial black ceramic finish trimmed with polished 24K gold borders and amber jewel tones.',
    accentColor: '#D4AF37',
    secondaryAccent: '#F59E0B',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'pure-black-neon',
    cornerRadius: 8,
    taskbarBlur: 15,
    startMenuBlur: 18,
    notificationBlur: 15,
    hideRecommended: true,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'obsidian.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="gold" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23000000"/><stop offset="50%" stop-color="%2378350f"/><stop offset="100%" stop-color="%23d4af37"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23gold)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #78350f 50%, #d4af37 100%)',
  },
  {
    id: 'cobalt-porcelain',
    name: 'Cobalt & Porcelain',
    category: 'Minimalist',
    description: 'Pristine Ming porcelain aesthetic pairing ultra-deep cobalt blue with crisp white ice borders and balanced spacing.',
    accentColor: '#0047AB',
    secondaryAccent: '#E1EBF5',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 8,
    taskbarBlur: 18,
    startMenuBlur: 20,
    notificationBlur: 18,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'cobalt-porcelain.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="cobalt" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23021124"/><stop offset="50%" stop-color="%230047ab"/><stop offset="100%" stop-color="%23e1ebf5"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23cobalt)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #021124 0%, #0047ab 50%, #e1ebf5 100%)',
  },

  // ------------------------------------------------------------
  // Retro & Aero Category
  // ------------------------------------------------------------
  {
    id: 'google-assistant-wave',
    name: 'Google Assistant Wave',
    category: 'Retro & Aero',
    description: 'Playful kinetic wave colors with Google blue, red, yellow, and green accents across an authentic dark acrylic shell.',
    accentColor: '#4285F4',
    secondaryAccent: '#EA4335',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 10,
    taskbarBlur: 20,
    startMenuBlur: 20,
    notificationBlur: 18,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'google-assistant-wave.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="wave" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%234285f4"/><stop offset="33%" stop-color="%23ea4335"/><stop offset="66%" stop-color="%23fbbc05"/><stop offset="100%" stop-color="%2334a853"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23wave)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #4285f4 0%, #ea4335 33%, #fbbc05 66%, #34a853 100%)',
  },
  {
    id: 'aero-glass',
    name: 'Aero Glass Classic',
    category: 'Retro & Aero',
    description: 'Windows 7 Aero-inspired crystalline blues and subtle WinUI 3 borders for a modern glass revival.',
    accentColor: '#0078D4',
    secondaryAccent: '#60CDFF',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 8,
    taskbarBlur: 18,
    startMenuBlur: 20,
    notificationBlur: 16,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: false,
    removeDropShadows: false,
    wallpaperFileName: 'default-dark.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="aero" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23004578"/><stop offset="50%" stop-color="%230078d4"/><stop offset="100%" stop-color="%2360cdff"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23aero)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #004578 0%, #0078d4 50%, #60cdff 100%)',
  },
  {
    id: 'crucifix-dark',
    name: 'Blue & White Christian Crucifix Dark',
    category: 'Retro & Aero',
    description: 'Sacred cathedral navy matched with radiant cerulean blue spires and solemn acrylic glass depth.',
    accentColor: '#062D7C',
    secondaryAccent: '#2760A7',
    isLightMode: false,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 10,
    taskbarBlur: 20,
    startMenuBlur: 20,
    notificationBlur: 20,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'crucifix-dark.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="crossdark" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%2303153b"/><stop offset="50%" stop-color="%23062d7c"/><stop offset="100%" stop-color="%232760a7"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23crossdark)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #03153b 0%, #062d7c 50%, #2760a7 100%)',
  },
  {
    id: 'crucifix-light',
    name: 'Blue & White Christian Crucifix Light',
    category: 'Retro & Aero',
    description: 'Serene church nave light mode with crisp cathedral cobalt lines over illuminated white marble.',
    accentColor: '#062D7C',
    secondaryAccent: '#2760A7',
    isLightMode: true,
    taskbarMode: 'blur',
    materialStyle: 'fluent-acrylic',
    cornerRadius: 10,
    taskbarBlur: 16,
    startMenuBlur: 18,
    notificationBlur: 16,
    hideRecommended: false,
    compactSearch: false,
    dynamicNotificationHeight: true,
    removeDropShadows: false,
    wallpaperFileName: 'crucifix-light.jpg',
    wallpaperUrl:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="crosslight" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="%23f0f4f8"/><stop offset="50%" stop-color="%23cfe0f5"/><stop offset="100%" stop-color="%23062d7c"/></linearGradient></defs><rect width="100%" height="100%" fill="url(%23crosslight)"/></svg>',
    previewGradient: 'linear-gradient(135deg, #f0f4f8 0%, #cfe0f5 50%, #062d7c 100%)',
  },
];
